name: End-to-end tests 🧪
on: 
  schedule:
    # runs tests every 5 minutes
    - cron: '5 * * * *'
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress daily tests 
        uses: cypress-io/github-action@v2
    