name: E2E  🧪
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 4 * * * *' 
    #run every day
    
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: run pipeline
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Run test every day
        uses: cypress-io/github-action@v2