name: E2E  🧪
on:
  schedule:
    - cron: '00 1 * * 1-5'  
    #run every day At 1 AM
    
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: run pipeline
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Run test every day
        uses: cypress-io/github-action@v3
